config/routes.rb
Bid::Application.routes.draw do
  root "projects#index"
  get "projects/index"
  
  devise_for :users
  
  resources :projects do
    resources :comments do
        delete "delete"
    end
    member do
        get "show_offers"
        post "comment"
    end
  end

  namespace :admin do
    resources :roads
    resources :projects
    resources :users
    resources :companies
    resources :noise_barrier_types
    resources :cities
    resources :road_names
    resources :offers
  end

resources :companies
resources :offers
resources :comments

resources :admin
resources :searches

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  validates :company_id, presence: true
  # 
  scope :by_ids, lambda {|ids|
    where(:id => ids) unless ids.empty?
  }
  # 
  belongs_to :company
  has_many :offers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :roads, dependent: :destroy
  has_many :road_names, through: :roads
  has_many :noise_barrier_contractors, dependent: :destroy
  has_many :noise_barriers, through: :roads  
  # 
  self.per_page = 20
  # 
  scope :current, -> { where current: true }
  scope :not_current, -> { where current: false }
  scope :gw, -> (company_id) { where(company_id: company_id)}
  # 
  accepts_nested_attributes_for :roads, allow_destroy: true
  # 
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :set_admin_project, only: [:show, :edit, :update, :destroy]
  before_filter do 
    redirect_to new_user_session_path unless current_user && current_user.is_admin
  end  

  # GET /admin/projects
  # GET /admin/projects.json
  def index
    @admin_projects = Project.paginate(:page => params[:page])
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
    @project = @admin_project
    @offers = @project.offers
    @roads = @project.roads  
    @noisebarriers = @project.noise_barriers
    @comments = @project.comments
    @comment = Comment.new
    # @search = @project


  end

  # GET /admin/projects/new
  def new
    @admin_project = Project.new
    a = @admin_project.roads.build
    b = a.noise_barriers.build
    b.noise_barrier_contractors.build

  end

  # GET /admin/projects/1/edit
  def edit
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @admin_project = Project.new(admin_project_params)
    puts "DEBUG " + admin_project_params.to_s

    respond_to do |format|
      if @admin_project.save
        # 
        # @admin_project.roads.each do |road|
        #  road.noise_barriers.each do |nb|
        #     nb.noise_barrier_contractors.each {|nbc| nbc.update_attribute(:project_id, @admin_project.id) }
        #   end
        # end


        # last.noise_barriers.last.noise_barrier_contractors.first.company.name
        # 
        format.html { redirect_to admin_project_path(@admin_project), notice: 'Projekt został dodany.' }
        format.json { render action: 'show', status: :created, location: @admin_project }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_project.errors, status: :unprocessable_entity }
      end
    end




  end

  # PATCH/PUT /admin/projects/1
  # PATCH/PUT /admin/projects/1.json
  def update
    respond_to do |format|
      if @admin_project.update(admin_project_params)
        format.html { redirect_to admin_projects_path, notice: 'Projekt został zaktualizowany.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @admin_project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_project
      @admin_project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_project_params
      # params[:admin_project]
      params.require(:project).permit!

    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :sort_column, :sort_direction, only: :index
	before_action :set_project, only: [:show, :show_offers, :comment]

  def comment 
    if comment_params[:comment].length > 0
      @comment = @project.comments.new(comment_params) 
      if @comment.save
        redirect_to @project
      else
        render :show
      end
    else
        redirect_to @project
    end
  end

  def destroy
  end
  
  def index    
    if params[:search]
      @search = Search.find(params[:search])
      if @search.projects.empty?
        @projects = nil
      else
        @projects = Project.by_ids(@search.projects.map(&:id)).page(params[:page]).order(sort_column + " " + sort_direction)
      end
    else 
      @projects ||= Project.paginate(:page => params[:page]).order(sort_column + " " + sort_direction)  
      @search = Search.new(page: "project")      
    end
  end

  def show
    @comment = Comment.new
    @search = @project
  end

  def show_offers
  	@offers = @project.offers
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      @offers = @project.offers
      @roads = @project.roads 
      @noisebarriers = @project.noise_barriers
      @comments = @project.comments
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:id, :name, :noisebarrier_id, :company_id)
    end

    def sort_column
      Project.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def comment_params
      params.require(:comment).permit!
    end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def search_helper search
		result = ""
		search.attributes.each { |key, value|
			if ((key == "title") && (!value.to_s.eql? ""))
				puts key.to_s + " >>>>>>>> " + value.to_s
				result = result.to_s + "Nazwa projektu: ".to_s + value.to_s + " ".to_s end
			if key == "gw_id" && !value.nil?
				result = result.to_s + "Generalny Wykonawca: ".to_s + Company.find(value).name.to_s + " ".to_s end
			if key == "road_id" && !value.nil?
				result = result.to_s + "Droga: ".to_s + RoadName.find(value).name.to_s + " ".to_s end
			if key == "noise_barrier_type_id" && !value.nil? 
				result = result.to_s + "Typ ekranów: " + NoiseBarrierType.find(value).name.to_s + " ".to_s end
			if key == "noise_barrier_contractor_id" && !value.nil? 
				result = result.to_s + "Wykonawca ekranów: ".to_s + Company.find(value).name.to_s + " ".to_s end
		}
		unless result == "" 
			result = "Wyszukiwanie >> ".to_s + result.to_s
		end
		result
	end
end

app/views/admin/projects/_form.html.erb
<%= simple_form_for(@admin_project, url:  (@admin_project.new_record? ? admin_projects_path : admin_project_path)) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name, label: "Nazwa projektu" %>
  </div>
  <%= f.input :tender_opening_date, as: :date, label: "Data otwarcia ofert" %>
  <%= f.input :lead_time, label: "Termin realizacji" %>
  <%= f.input :current, label: false, inline_label: "Aktualny" %>
  <%= f.association :company, label: "Generalny Wykonawca" %>
  <fieldset class="scheduler-border">
    <legend class="scheduler-border">Drogi</legend>
    <%= f.fields_for :roads do |builder| %>
      <%= builder.association :road_name, label: false %>
      <fieldset class="scheduler-border">
        <legend class="scheduler-border">Ekrany</legend>
        <fieldset class="scheduler-border">
          <%= builder.fields_for :noise_barriers do |nb| %>
            <%= nb.input :quantity, label: "Ilość ekranów" %><br />
            <%= nb.association :noise_barrier_type, label: "Typ ekranów" %><br />
            <%= nb.association :companies, as: :collection_select, label: "Wykonawca ekranów" %><br />
          </fieldset>
          <%= link_to_add_fields "Dodaj ekran", builder, :noise_barriers  %>
      </fieldset>
      <%= link_to_add_fields "Dodaj drogę", f, :roads  %>
        <% end %>
    <% end %>
  </fieldset>
  <div class="form-inputs">
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/projects/_noise_barrier_fields.html.erb
<fieldset class="scheduler-border">
  <%= f.input :quantity, label: "Ilość ekranów" %><br />      
  <%= f.association :noise_barrier_type, label: "Typ ekranów" %><br />      
  <%= f.association :companies, as: :collection_select, label: "Wykonawca ekranów" %><br />      
	<%= link_to "usuń ekran", "#", class: "remove_fields" %>
	<%= f.input :_destroy, as: :boolean, as: :hidden  %>
</fieldset>

app/views/admin/projects/_road_fields.html.erb
<fieldset> 
	<%= f.association :road_name, label: false %>
	<%= link_to "usuń drogę", "#", class: "remove_fields" %>
	<%= f.input :_destroy, as: :boolean, as: :hidden  %>
	<fieldset class="scheduler-border">
        <legend class="scheduler-border">Ekrany</legend>
	<%= link_to_add_fields "Dodaj ekran", f, :noise_barriers  %>
	</fieldset>
</fieldset>

app/views/admin/projects/edit.html.erb
<h1>Edycja projektu</h1>

<%= render 'form' %>

<%= link_to 'Cofinj', admin_projects_path %>

app/views/admin/projects/index.html.erb
<h1>Projekty</h1>

<table class="table table-striped">
    <thead>
      <tr>      
        <th>ID</th>
        <th>Nazwa projektu</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @admin_projects.each do |p| %>
        <tr>        
          <td><%= p.id %></td>
          <td><%= link_to p.name, admin_project_path(p) %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_admin_project_path(p), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        admin_project_path(p),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>                    
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<div class="digg_pagination">
  <%= will_paginate @admin_projects, :container => false if @admin_projects.present? %>
</div>
<br>
<%= button_to "Dodaj nowy projekt", new_admin_project_path, method: :"get", class: :"btn btn" %>

app/views/admin/projects/new.html.erb
<h1>Nowy projekt</h1>

<%= render 'form' %>

<%= link_to 'Cofnij', admin_projects_path %>

app/views/admin/projects/show.html.erb
<%- model_class = Project -%>
<fieldset class="scheduler-border">
  <legend class="scheduler-border"><h3>Projekt</h3></legend>
    <table class="one">
      <tbody>
        <tr>
          <td class="a"><strong>Nazwa projektu:</strong></td>
          <td class="a"><%= @project.name %></td>
        </tr>
        <tr>
          <td class="a"><strong>Data otwarcia ofert:</strong></td>
          <td class="a"><%= @project.tender_opening_date.strftime("%m/%d/%Y") %></td>
        </tr>
        <tr>
          <td class="a"><strong>Data zakończenia:</strong></td>
          <td class="a"><%= @project.lead_time %></td>
        </tr>
        <tr>   
          <td class="a"><strong>Generalny Wykonawca:</strong></td>
          <td class="a"><%= @project.company.name %></td>
      </tbody>
    </table>
</fieldset>

<p></p>
<fieldset class="scheduler-border">
  <legend class="scheduler-border"><h3>Złożone oferty</h3></legend>
    <table class="one">
      <thead>
        <tr>
        	<th class="a">Numer oferty</th>
        	<th class="a">Data złożenia oferty</th>
        	<th class="a">Adresat oferty</th>
        </tr>
      </thead>
      <tbody>
      	<% @offers.each do |o| %>
      	<tr>
      		<td class="a"><%= o.offer_no %></td>
      		<td class="a"><%= o.offer_date.strftime("%d/%m/%Y") %></td>
      		<td class="a"><%= o.company.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</fieldset>

<p></p>
<fieldset class="scheduler-border">
  <legend class="scheduler-border"><h3>Drogi lub lokalizacje</h3></legend>
    <table class="one">
      <thead>
        <tr>
        	<th class="a">Nazwa drogi lub lokalizacji</th>
        </tr>
      </thead>
      <tbody>
    		<% @roads.each do |r| %>
      		<tr>
      			<td class="a"><%= r.road_name.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</fieldset>

<p></p>
<fieldset class="scheduler-border">
  <legend class="scheduler-border"><h3>Zestawienie ekranów</h3></legend>
    <table class="one">
      <thead>
        <tr>
        	<th class="a">Powierzchnia</th>
        	<th class="a">Typ ekranu</th>
        	<th class="a">Droga</th>
        	<th class="a">Wykonawca ekanów</th>
        </tr>
      </thead>
      <tbody>
    		<% @noisebarriers.each do |n| %>
    		<tr>
    			<td class="a"><%= n.quantity %> m2</td>
          <td class="a"><%= n.noise_barrier_type.name %></td>
          <td class="a"><%= n.road.road_name.name %></td>
          <td class="a"><%= n.companies.first.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</fieldset>

<p></p>
<fieldset class="scheduler-border">
  <legend class="scheduler-border"><h3>Notatki</h3></legend>
    <%= form_for @comment, url: comment_project_path, html: {class: "nifty_form"} do |com| %>
      <%= com.label "Dodaj nową notatkę" %>
      <%= com.text_area :comment, size: "120x3" %>
      </br>
      <%= com.submit "Dodaj" %>
    <% end %>
    <table class="one">
      <thead>
        <tr>
    			<th class="a">Data wpisu</th>
          <th class="a">Notatka</th>
        	<th class="a">Akcja</th>
        </tr>
      </thead>
      <tbody>
    		<% @comments.each do |c| %>
    		  <tr>
    			 <td class="a"><%= c.created_at.try(:strftime,"%d/%m/%Y") %></td>
           <td class="a"><%= c.comment %></td>
    			 <td class="a"><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            project_comment_delete_path(@project,c),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Czy na pewno chcesz skasować?')) },
                            :class => 'btn btn-mini btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</fieldset>
<%= link_to 'Cofnij', admin_projects_path %>