config/routes.rb
Bid::Application.routes.draw do
  root "projects#index"
  get "projects/index"
  
  devise_for :users
  
  resources :projects do
    resources :comments do
        delete "delete"
    end
    member do
        get "show_offers"
        post "comment"
    end
  end

  namespace :admin do
    resources :roads
    resources :projects
    resources :users
    resources :companies
    resources :noise_barrier_types
    resources :cities
    resources :road_names
    resources :offers
  end

resources :companies
resources :offers
resources :comments

resources :admin
resources :searches

end

app/models/road.rb
class Road < ActiveRecord::Base
  validates :road_name_id, presence: true
  delegate :name, to: :road_name
  belongs_to :project
  belongs_to :road_name
  has_many :noise_barriers, dependent: :destroy
  # 
  accepts_nested_attributes_for :noise_barriers, allow_destroy: true

end

app/controllers/admin/roads_controller.rb
class Admin::RoadsController < ApplicationController
  before_action :set_admin_road, only: [:show, :edit, :update, :destroy]
  before_filter do 
    redirect_to new_user_session_path unless current_user && current_user.is_admin
  end  

  # GET /admin/roads
  # GET /admin/roads.json
  def index
    @admin_roads = Road.all
  end
  # GET /admin/roads/new
  def new
    @admin_road = Road.new
  end

  # GET /admin/roads/1/edit
  def edit
  end

  # POST /admin/roads
  # POST /admin/roads.json
  def create
    @admin_road = Road.new(admin_road_params)

    respond_to do |format|
      if @admin_road.save
        format.html { redirect_to admin_roads_path, notice: 'Road was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_road }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_road.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/roads/1
  # PATCH/PUT /admin/roads/1.json
  def update
    respond_to do |format|
      if @admin_road.update(admin_road_params)
        format.html { redirect_to admin_roads_path, notice: 'Road was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_road.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/roads/1
  # DELETE /admin/roads/1.json
  def destroy
    @admin_road.destroy
    respond_to do |format|
      format.html { redirect_to admin_roads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_road
      @admin_road = Road.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_road_params
      params.require(:road).permit!
    end
end

app/helpers/admin/roads_helper.rb
module Admin::RoadsHelper
end

app/views/admin/roads/_form.html.erb
<%= simple_form_for(@admin_road, url: (@admin_road.new_record? ? admin_roads_path : admin_road_path)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <%= f.association :road_name, label: "Nazwa" %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/roads/edit.html.erb
<h1>Editing admin_road</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_roads_path %>

app/views/admin/roads/index.html.erb
<h1>Listing admin_roads</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Nazwa</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_roads.each do |admin_road| %>
      <tr>
        <td><%= admin_road.id %></td>
        <td><%= admin_road.name %></td>
        <td><%= link_to 'Edit', edit_admin_road_path(admin_road) %></td>
        <td><%= link_to 'Destroy',admin_road_path(admin_road), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Road', new_admin_road_path %>

app/views/admin/roads/new.html.erb
<h1>New admin_road</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_roads_path %>