config/routes.rb
Bid::Application.routes.draw do
  root "projects#index"
  get "projects/index"
  
  devise_for :users
  
  resources :projects do
    resources :comments do
        delete "delete"
    end
    member do
        get "show_offers"
        post "comment"
    end
  end

  namespace :admin do
    resources :roads
    resources :projects
    resources :users
    resources :companies
    resources :noise_barrier_types
    resources :cities
    resources :road_names
    resources :offers
  end

resources :companies
resources :offers
resources :comments

resources :admin
resources :searches

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # 
  self.per_page = 20
  # 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter do 
    redirect_to new_user_session_path unless current_user && current_user.is_admin
  end  
  def index
    @users = User.paginate(:page => params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end


  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(admin_user_params)
        format.html { redirect_to admin_users_path, notice: 'Dane użytkownik został zaktualizowane.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @user = User.new(admin_user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'Użytkownik został dodany.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /admin/roads/1
  # DELETE /admin/roads/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end


  private

  def admin_user_params
    params.require(:user).permit!
  end

end

app/views/admin/users/_form.html.erb
<%= simple_form_for(@user, url: (@user.new_record? ? admin_users_path : admin_user_path)) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
        <%= f.input :email, label: "E-mail", disabled: (@user.new_record? ? false : true)%>
        <%  if  @user.new_record? %>
          <%= f.input :password %>
          <%= f.input :password_confirmation %>
        <% end %>
        <%= f.input :is_admin  %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edycja danych użytkownika</h1>

<%= render 'form' %>

<%= link_to 'Cofnij', admin_index_path %>

app/views/admin/users/index.html.erb
<h1>Użytkownicy</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>e-mail</th>
    <th>Czy jest administratorem</th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |p| %>
      <tr>
        <td><%= p.id %></td>
        <td><%= p.email %></td>
        <td><%= "Tak" if p.is_admin? %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_user_path(p), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_user_path(p),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<div class="digg_pagination">
  <%= will_paginate @users, :container => false if @users.present? %>
</div>
<br>
<%= button_to "Dodaj użytkownika", new_admin_user_path, method: :"get", class: :"btn btn" %>

app/views/admin/users/new.html.erb
<h1>Nowy użytkownik</h1>

<%= render 'form' %>

<%= link_to 'Cofnij', admin_users_path %>